// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDs8f8LnDeRTtGfQpkVUcUva3vCUMN9jA',
    appId: '1:462522344037:web:ca1faff134c94c0f951c8c',
    messagingSenderId: '462522344037',
    projectId: 'doctor-consultation-1684c',
    authDomain: 'doctor-consultation-1684c.firebaseapp.com',
    storageBucket: 'doctor-consultation-1684c.firebasestorage.app',
    measurementId: 'G-807NBBMXT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKNmYYLhZ7l9l7y1GcivtICrN1iWca6w',
    appId: '1:462522344037:android:3439eb5a0e04a31f951c8c',
    messagingSenderId: '462522344037',
    projectId: 'doctor-consultation-1684c',
    storageBucket: 'doctor-consultation-1684c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC2U932Gbc63wOGBkIZ2mNWWmiVX0R6d4',
    appId: '1:462522344037:ios:c6ac2f1d409d9cac951c8c',
    messagingSenderId: '462522344037',
    projectId: 'doctor-consultation-1684c',
    storageBucket: 'doctor-consultation-1684c.firebasestorage.app',
    iosBundleId: 'com.example.drServ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDs8f8LnDeRTtGfQpkVUcUva3vCUMN9jA',
    appId: '1:462522344037:web:bab65698f9d77805951c8c',
    messagingSenderId: '462522344037',
    projectId: 'doctor-consultation-1684c',
    authDomain: 'doctor-consultation-1684c.firebaseapp.com',
    storageBucket: 'doctor-consultation-1684c.firebasestorage.app',
    measurementId: 'G-KZ08S5ZXYG',
  );
}
